---
title: "ABF"
output: html_document
---

## Wakefield ABF (approximate bayes factor)?

>> Jon Wakefield 2008. Genetic Epidemiology
>> Bayes factors for genome-wide association studies: comparison with P-values

## P-values in genetic association studies

1. A arbituary Pval cutoff to choose significant findings does not reflect statistical power of the given test, which is a function of maf and sample size. 
2. Therefore, this practice punish studies of smaller sample size, likewise the rare variants.

## Bayes factor

$$BF = \frac{Pr(y|H_0)}{Pr(y|H_1)}$$

$$\frac{Pr(H_0|y)}{Pr(H_1|y)} = \frac{Pr(y|H_0)}{Pr(y|H_1)} * \frac{Pr(H_0)}{Pr(H_1)}$$

Significance measure: $\frac{Pr(H_0|y)}{Pr(H_1|y)}$

## Wakefield Approximate Bayes Factor to against the null hypothesis

$$WAFB = \sqrt{V / (V + W)} e^{(Wz^2 / 2 (V+W))}$$

## ?s

>> Why it is better than P-values?
>> How to understand ABF depends on both p-value and power?
>> How to understand when power is high, probability of null and alternative hypothesis are both high?

## Wald statistics

```{r}
x = rnorm(1e2, 0, 1)
y = x + rnorm(1e2, 0, 2)

(fit = summary(lm(y ~ x)))
coef = fit$coefficients
wald = coef["x", "Estimate"] / coef["x", "Std. Error"]
wald = wald^2
coef["x", "t value"] ^ 2
1 - pchisq(wald, df = 1)
```
